### ISSUE TITLE
Schedule Tab Only Displays First Three Classes

### ISSUE THREAD

**Issue by tektaxi** [Aspine/aspine#140]
Right now only CM through Second Period is displayed, we need to fix that so we see everything.

**Comment by psvenk** [comment]
Thank you for opening this issue. There was an initial fix to this in dc8a852bce, but I think the school changed the schedule format slightly since then so we need to change the schedule scraping code once again to accommodate.

**Comment by psvenk** [comment]
A related issue is that no classes are shown whatsoever on a day when school is not in session.

**Comment by tektaxi** [comment]
Is there a fix for this in #145 ? I saw that a covid schedule was added, but I'm not sure if this applies to the schedule tab too or just the clock.

**Comment by psvenk** [comment]
@tektaxi This is not addressed in #145; that only deals with the clock (frontend) and not with the schedule scraping (backend). However, it may be possible to fix this entirely in the frontend if dc8a852bce is the culprit (that is, if reverting the changes made in that commit would leave us with the necessary information to format the schedule properly).

By the way, I removed my self-assignment because I had intended to work on this but I have not begun any work on it, so anyone is free to take this on (no pressure).

**Comment by psvenk** [comment]
Addendum: in any case it would probably be a good idea to make some changes on the backend so that the semantic structure of the schedule object matches the real structure of the schedule (and it is not just the frontend shuffling things around). This would make it easier to show older (pre-covid) schedules properly in imported data and also to make it easier to support covid schedules after school reopens, because both covid and non-covid schedules would be stored similarly if not identically.

**Comment by tektaxi** [comment]
This is still an issue and makes the schedule tab essentially useless so if we could try and fix this soon that would be really helpful. I'm not really sure how to tackle it because I'm not super comfortable with Node so if someone else could that would be nice.

**Comment by psvenk** [comment]
@tektaxi Yes, this should be given priority and I just now labelled it as such. By the way, my tagging of version 2.5.0 was simply because the second quarter has now begun and we have a rather large batch of changes that we should try to get onto the production server.

**Comment by psvenk** [comment]
The schedule scraper is going to be reworked as part of #184, so this issue will probably also be fixed (even if the schedule turns out not to be exposed by the REST API).

**Comment by tektaxi** [comment]
@psvenk When we rework the schedule scrape we shouldn't scrape for the current date anymore because otherwise, we can't view the schedule on Wednesdays or Weekends. I would recommend just grabbing the schedule for the current quarter, or even having a dropdown menu to select the quarter like on Aspen.

**Comment by psvenk** [comment]
@tektaxi Yes, this is the plan. Thanks for pointing this out, and sorry for not making myself more clear. The REST API provides a way to find which quarter is the current one (which goes toward fixing #82), so this will not be too hard to implement.
